# define macro 'message_status'
macro(message_status string)
    message(STATUS "${string}")
endmacro()

# define macro 'message_fatal_error'
macro(message_fatal_error string)
    message(FATAL_ERROR "${string}")
endmacro()

# define macro 'set_home_prefix'
macro(set_home_prefix)
    if(${ARGC} EQUAL 0)
        if(WIN32)
            string(REPLACE "\\" "/" HOME_PREFIX "$ENV{USERPROFILE}")
        elseif(UNIX)
            set(HOME_PREFIX "$ENV{HOME}")
        else()
            message_fatal_error("Can't set HOME_PREFIX")
        endif()
    elseif("${ARGV0}" MATCHES "^$")
        set(HOME_PREFIX "")
    elseif("${ARGV0}" MATCHES "^[ \t\r\n]+.")
        message_status("Path starts with whitespace: '${ARGV0}'")
    elseif(NOT EXISTS "${ARGV0}")
        message_status("Not exists: '${ARGV0}'")
    elseif(NOT IS_DIRECTORY "${ARGV0}")
        message_status("Not is directory: '${ARGV0}'")
    else()
        set(HOME_PREFIX "${ARGV0}")
    endif()
endmacro()

# define macro 'set_packages_prefix'
macro(set_packages_prefix)
    if(NOT DEFINED "${DEFAULT_INSTALL_PREFIX}")
        set(
            DEFAULT_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}"
            CACHE
            PATH
            "Default CMAKE_INSTALL_PREFIX"
            FORCE
        )
    endif()
    if(${ARGC} EQUAL 0)
        set(CMAKE_INSTALL_PREFIX "${DEFAULT_INSTALL_PREFIX}")
    elseif("${ARGV0}" MATCHES "^$")
        set(CMAKE_INSTALL_PREFIX "")
    elseif("${ARGV0}" MATCHES "^[ \t\r\n]+.")
        message_status("Path starts with whitespace: '${ARGV0}'")
    elseif(NOT EXISTS "${ARGV0}")
        message_status("Not exists: '${ARGV0}'")
    elseif(NOT IS_DIRECTORY "${ARGV0}")
        message_status("Not is directory: '${ARGV0}'")
    else()
        set(CMAKE_INSTALL_PREFIX "${ARGV0}")
    endif()
endmacro()

# define macro 'set_downloads_prefix'
macro(set_downloads_prefix)
    if(${ARGC} EQUAL 0)
        set(DOWNLOADS_PREFIX "")
    elseif("${ARGV0}" MATCHES "^$")
        set(DOWNLOADS_PREFIX "")
    elseif("${ARGV0}" MATCHES "^[ \t\r\n]+.")
        message_status("Path starts with whitespace: '${ARGV0}'")
    elseif(NOT EXISTS "${ARGV0}")
        message_status("Not exists: '${ARGV0}'")
    elseif(NOT IS_DIRECTORY "${ARGV0}")
        message_status("Not is directory: '${ARGV0}'")
    else()
        set(DOWNLOADS_PREFIX "${ARGV0}")
    endif()
endmacro()

# define macro 'init'
macro(init)
    if(${ARGC} EQUAL 0)
        set_home_prefix()
        set_packages_prefix(${HOME_PREFIX}/.cmake/packages)
        set_downloads_prefix(${HOME_PREFIX}/.cmake/downloads)
    elseif("${ARGV0}" MATCHES "^$")
        set_home_prefix("")
        set_packages_prefix(${HOME_PREFIX}/.cmake/packages)
        set_downloads_prefix(${HOME_PREFIX}/.cmake/downloads)
    elseif("${ARGV0}" MATCHES "^[ \t\r\n]+.")
        message_status("Path starts with whitespace: '${ARGV0}'")
    elseif(NOT EXISTS "${ARGV0}")
        message_status("Not exists: '${ARGV0}'")
    elseif(NOT IS_DIRECTORY "${ARGV0}")
        message_status("Not is directory: '${ARGV0}'")
    else()
        set_home_prefix("${ARGV0}")
        set_packages_prefix(${HOME_PREFIX}/.cmake/packages)
        set_downloads_prefix(${HOME_PREFIX}/.cmake/downloads)
    endif()
endmacro()

# define macro 'download'
macro(download file_name url)
    if(NOT EXISTS "${DOWNLOADS_PREFIX}/${file_name}" AND NOT EXISTS "${DOWNLOADS_PREFIX}/${file_name}.md5")
        file(DOWNLOAD "${url}" "${DOWNLOADS_PREFIX}/${file_name}")
        file(MD5 "${DOWNLOADS_PREFIX}/${file_name}" "${file_name}.md5")
        file(WRITE "${DOWNLOADS_PREFIX}/${file_name}.md5" "${${file_name}.md5}")
        unset("${${file_name}.md5}")
        message_status("Downloaded '${url}' to '${DOWNLOADS_PREFIX}/${file_name}'")
        message_status("Downloaded md5 '${url}' to '${DOWNLOADS_PREFIX}/${file_name}.md5'")
    elseif(EXISTS "${DOWNLOADS_PREFIX}/${file_name}.md5")
        file(DOWNLOAD "${url}" "${DOWNLOADS_PREFIX}/${file_name}")
        file(READ "${DOWNLOADS_PREFIX}/${file_name}.md5" "old.${file_name}.md5")
        file(MD5 "${DOWNLOADS_PREFIX}/${file_name}" "new.${file_name}.md5")
        if("${old.${file_name}.md5}" STREQUAL "${new.${file_name}.md5}")
            unset("${old.${file_name}.md5}")
            unset("${new.${file_name}.md5}")
            message_status("Downloaded '${url}' to '${DOWNLOADS_PREFIX}/${file_name}'")
        else()
            file(REMOVE "${DOWNLOADS_PREFIX}/${file_name}")
            message_status("md5 check fail 'exist'/'new': '${old.${file_name}.md5}'/'${new.${file_name}.md5}'")
            unset("${old.${file_name}.md5}")
            unset("${new.${file_name}.md5}")
            message_fatal_error("Removed '${DOWNLOADS_PREFIX}/${file_name}'")
        endif()
    else()
        message_status("Exists '${DOWNLOADS_PREFIX}/${file_name}' or '${DOWNLOADS_PREFIX}/${file_name}.md5'")
    endif()
endmacro()
