set(CMAKE_SYSTEM_PROCESSOR "AMD64")
set(CMAKE_SYSTEM_NAME "Windows")

set(COMPILER_PATH "C:/Program Files/JetBrains/CLion 2022.2.1/bin/mingw/bin")

set(CMAKE_C_COMPILER   "${COMPILER_PATH}/gcc.exe")
set(CMAKE_CXX_COMPILER "${COMPILER_PATH}/g++.exe")
set(CMAKE_AR           "${COMPILER_PATH}/ar.exe")
set(CMAKE_LINKER       "${COMPILER_PATH}/ld.exe")
set(CMAKE_RC_COMPILER  "${COMPILER_PATH}/windres.exe")

set(ENV{PATH} "C:\\Program Files\\JetBrains\\CLion 2022.2.1\\bin\\mingw\\bin;$ENV{PATH}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
